# Form implementation generated from reading ui file 'commentsPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommentsWindow(object):
    def setupUi(self, CommentsWindow):
        CommentsWindow.setObjectName("CommentsWindow")
        CommentsWindow.resize(466, 476)
        CommentsWindow.setStyleSheet("background-color: rgb(255, 240, 234);")
        self.centralwidget = QtWidgets.QWidget(parent=CommentsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.booktitle = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.booktitle.setGeometry(QtCore.QRect(120, 80, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.booktitle.setFont(font)
        self.booktitle.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:10%\n"
"")
        self.booktitle.setReadOnly(True)
        self.booktitle.setObjectName("booktitle")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 130, 431, 301))
        self.tableView.setObjectName("tableView")
        CommentsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CommentsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 22))
        self.menubar.setObjectName("menubar")
        CommentsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CommentsWindow)
        self.statusbar.setObjectName("statusbar")
        CommentsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CommentsWindow)
        QtCore.QMetaObject.connectSlotsByName(CommentsWindow)

    def retranslateUi(self, CommentsWindow):
        _translate = QtCore.QCoreApplication.translate
        CommentsWindow.setWindowTitle(_translate("CommentsWindow", "MainWindow"))
        self.label.setText(_translate("CommentsWindow", "Комментарии"))
        self.label_2.setText(_translate("CommentsWindow", "Книга:"))