# Form implementation generated from reading ui file 'connectionPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectionWindow(object):
    def setupUi(self, ConnectionWindow):
        ConnectionWindow.setObjectName("ConnectionWindow")
        ConnectionWindow.resize(357, 245)
        ConnectionWindow.setStyleSheet("background-color: rgb(202, 200, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=ConnectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10%")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10%")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 10%;\n"
"color: black;\n"
"background-color: rgb(244, 244, 244);")
        self.pushButton.setObjectName("pushButton")
        ConnectionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ConnectionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 22))
        self.menubar.setObjectName("menubar")
        ConnectionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ConnectionWindow)
        self.statusbar.setObjectName("statusbar")
        ConnectionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConnectionWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectionWindow)

    def retranslateUi(self, ConnectionWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectionWindow.setWindowTitle(_translate("ConnectionWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("ConnectionWindow", "127.0.0.1"))
        self.lineEdit_2.setText(_translate("ConnectionWindow", "9000"))
        self.lineEdit_2.setPlaceholderText(_translate("ConnectionWindow", "9000"))
        self.label_2.setText(_translate("ConnectionWindow", "Подключение"))
        self.label_3.setText(_translate("ConnectionWindow", "IP-адрес"))
        self.label_4.setText(_translate("ConnectionWindow", "Порт"))
        self.pushButton.setText(_translate("ConnectionWindow", "Подключиться"))
