# Form implementation generated from reading ui file 'logInPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogInWindow(object):
    def setupUi(self, LogInWindow):
        LogInWindow.setObjectName("LogInWindow")
        LogInWindow.resize(343, 464)
        LogInWindow.setStyleSheet("background-color: rgb(202, 200, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=LogInWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(38, 50, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(38, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(38, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputEmail = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(38, 170, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.inputEmail.setFont(font)
        self.inputEmail.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputEmail.setObjectName("inputEmail")
        self.accountType = QtWidgets.QComboBox(parent=self.centralwidget)
        self.accountType.setGeometry(QtCore.QRect(40, 100, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.accountType.setFont(font)
        self.accountType.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:3%;")
        self.accountType.setObjectName("accountType")
        self.accountType.addItem("")
        self.accountType.addItem("")
        self.logIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logIn.setGeometry(QtCore.QRect(40, 320, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.logIn.setFont(font)
        self.logIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logIn.setStyleSheet("background-color: rgb(99, 101, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10%\n"
"")
        self.logIn.setObjectName("logIn")
        self.btnToRegistrationPage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToRegistrationPage.setGeometry(QtCore.QRect(42, 390, 271, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.btnToRegistrationPage.setFont(font)
        self.btnToRegistrationPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnToRegistrationPage.setFlat(True)
        self.btnToRegistrationPage.setObjectName("btnToRegistrationPage")
        self.inputPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(40, 250, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPassword.setFont(font)
        self.inputPassword.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputPassword.setObjectName("inputPassword")
        LogInWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LogInWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 343, 22))
        self.menubar.setObjectName("menubar")
        LogInWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LogInWindow)
        self.statusbar.setObjectName("statusbar")
        LogInWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogInWindow)
        QtCore.QMetaObject.connectSlotsByName(LogInWindow)

    def retranslateUi(self, LogInWindow):
        _translate = QtCore.QCoreApplication.translate
        LogInWindow.setWindowTitle(_translate("LogInWindow", "MainWindow"))
        self.label.setText(_translate("LogInWindow", "Авторизация"))
        self.label_2.setText(_translate("LogInWindow", "Выберите тип аккаунта"))
        self.label_4.setText(_translate("LogInWindow", "Почта"))
        self.label_5.setText(_translate("LogInWindow", "Пароль"))
        self.accountType.setItemText(0, _translate("LogInWindow", "Пользователь"))
        self.accountType.setItemText(1, _translate("LogInWindow", "Администратор"))
        self.logIn.setText(_translate("LogInWindow", "Вход"))
        self.btnToRegistrationPage.setText(_translate("LogInWindow", "Ещё нет аккаунта? Зарегистрироваться"))
