# Form implementation generated from reading ui file 'logInPage.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogInWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 529)
        MainWindow.setStyleSheet("background-color: rgb(202, 200, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(98, 80, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(98, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(98, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputEmail = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(98, 210, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.inputEmail.setFont(font)
        self.inputEmail.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputEmail.setObjectName("inputEmail")
        self.accountType = QtWidgets.QComboBox(parent=self.centralwidget)
        self.accountType.setGeometry(QtCore.QRect(100, 121, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.accountType.setFont(font)
        self.accountType.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:3%;")
        self.accountType.setObjectName("accountType")
        self.accountType.addItem("")
        self.accountType.addItem("")
        self.logIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logIn.setGeometry(QtCore.QRect(100, 350, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.logIn.setFont(font)
        self.logIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logIn.setStyleSheet("background-color: rgb(99, 101, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10%\n"
"")
        self.logIn.setObjectName("logIn")
        self.btnToRegistrationPage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToRegistrationPage.setGeometry(QtCore.QRect(102, 430, 271, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.btnToRegistrationPage.setFont(font)
        self.btnToRegistrationPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnToRegistrationPage.setFlat(True)
        self.btnToRegistrationPage.setObjectName("btnToRegistrationPage")
        self.inputPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(100, 290, 271, 31))
        self.inputPassword.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputPassword.setObjectName("inputPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Авторизация"))
        self.label_2.setText(_translate("MainWindow", "Выберите тип аккаунта"))
        self.label_4.setText(_translate("MainWindow", "Почта"))
        self.label_5.setText(_translate("MainWindow", "Пароль"))
        self.accountType.setItemText(0, _translate("MainWindow", "Пользователь"))
        self.accountType.setItemText(1, _translate("MainWindow", "Администратор"))
        self.logIn.setText(_translate("MainWindow", "Вход"))
        self.btnToRegistrationPage.setText(_translate("MainWindow", "Ещё нет аккаунта? Зарегистрироваться"))
