from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_ProfileWindow(object):
    def setupUi(self, ProfileWindow):
        ProfileWindow.setObjectName("ProfileWindow")
        ProfileWindow.resize(335, 453)
        ProfileWindow.setStyleSheet("background-color: rgb(202, 200, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=ProfileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btnchangeOrSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnchangeOrSave.setGeometry(QtCore.QRect(60, 340, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.btnchangeOrSave.setFont(font)
        self.btnchangeOrSave.setStyleSheet("background-color: rgb(99, 101, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10%")
        self.btnchangeOrSave.setObjectName("btnchangeOrSave")
        self.email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email.setGeometry(QtCore.QRect(60, 140, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10%")
        self.email.setPlaceholderText("")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(60, 260, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10%")
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        ProfileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ProfileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 22))
        self.menubar.setObjectName("menubar")
        ProfileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ProfileWindow)
        self.statusbar.setObjectName("statusbar")
        ProfileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileWindow)

    def retranslateUi(self, ProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "MainWindow"))
        self.label.setText(_translate("ProfileWindow", "Профиль пользователя"))
        self.btnchangeOrSave.setText(_translate("ProfileWindow", "Изменить"))
        self.label_2.setText(_translate("ProfileWindow", "Почта"))
        self.label_3.setText(_translate("ProfileWindow", "Пароль"))
