# Form implementation generated from reading ui file 'registratePage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrateWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(344, 449)
        MainWindow.setStyleSheet("background-color: rgb(202, 200, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(28, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputEmail = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(28, 140, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.inputEmail.setFont(font)
        self.inputEmail.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputEmail.setObjectName("inputEmail")
        self.btnRegistrate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegistrate.setGeometry(QtCore.QRect(30, 290, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.btnRegistrate.setFont(font)
        self.btnRegistrate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnRegistrate.setStyleSheet("background-color: rgb(99, 101, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10%\n"
"")
        self.btnRegistrate.setObjectName("btnRegistrate")
        self.btnToLogInPage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnToLogInPage.setGeometry(QtCore.QRect(32, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.btnToLogInPage.setFont(font)
        self.btnToLogInPage.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnToLogInPage.setFlat(True)
        self.btnToLogInPage.setObjectName("btnToLogInPage")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.inputPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(30, 230, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPassword.setFont(font)
        self.inputPassword.setStyleSheet("background-color: rgb(235, 235, 235);\n"
"border-radius:10%")
        self.inputPassword.setObjectName("inputPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 344, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label_4.setText(_translate("MainWindow", "Почта"))
        self.label_5.setText(_translate("MainWindow", "Пароль"))
        self.btnRegistrate.setText(_translate("MainWindow", "Регистрация"))
        self.btnToLogInPage.setText(_translate("MainWindow", "Уже есть аккаунт? Войти"))
        self.label_6.setText(_translate("MainWindow", "Пользователь"))
